### ISSUE TITLE
Clicking "download safe launcher" on website downloads demo app

### ISSUE THREAD

**Issue by mowliv** [maidsafe/safe_app_nodejs#28] opened 2017-02-15 03:50 UTC
(not sure which repo this should be in, so pls move if needed)

Downloaded demo app a few times by hitting "download safe launcher" button on https://maidsafe.net/demo_app_downloading.html#demo_app

![image](https://cloud.githubusercontent.com/assets/4602829/22959895/9ae8fa12-f2ee-11e6-9650-1c5cdf2b9df3.png)

**Comment by krishnaIndia** [comment] 2017-02-15 05:34
@mowliv, you will have to start the launcher application and register an account. Leave the launcher running and then start using the safe apps. [Here](https://maidsafe.readme.io/docs/install-launcher) is a tutorial on how to use the launcher and the demo app. Hope it helps, if you still have a problem feel free to report under the [safe_launcher](https://github.com/maidsafe/safe_launcher/issues) repository

**Comment by mowliv** [comment] 2017-02-15 14:51
@krishnaIndia you didn't understand my report. I was initially unable to download the launcher app because when I clicked the appropriate button on the website it instead downloaded the demo app.

**Comment by frabrunelle** [comment] 2017-02-15 15:47
@mowliv thank you for opening this GitHub issue 🙂

I just found what the problem is.

There is a typo on the demo app page: https://maidsafe.net/demo_app_downloading.html#demo_app

the "Download SAFE Launcher" button should point to `./safe_launcher_downloading.html#launcher?download` instead of `./safe_launcher_downloading.html#laucher?download`.

so because the word "launcher" has a typo, it downloads the demo app instead of the launcher.

we'll get this fixed quickly. thanks again, @mowliv!

**Comment by frabrunelle** [comment] 2017-02-15 18:18
Update: We've fixed this issue.

The download link for SAFE Launcher on https://maidsafe.net/demo_app_downloading.html#demo_app seems to work fine now 👍

**Comment by mowliv** [comment] 2017-02-15 23:55
Yes, working now for me. Cool.

On Wed, Feb 15, 2017 at 10:18 AM, Francis Brunelle <notifications@github.com

**Comment by krishnaIndia** [comment] 2017-02-16 05:09
@mowliv, updated the website. Thanks for reporting the issue. @frabrunelle confirmed that the issue is resolved. Closing the issue for now.

**Closed by krishnaIndia** 2017-02-16 05:09 UTC
