### ISSUE TITLE
Open URI error in examples

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_app_nodejs#25] opened 2017-02-10 17:58 UTC
MacOS,
rust 1.14.0

I've built the app as per instructions, tests pass, setup the browser with authentication plugin (which works fine as far as I can tell), and i'm trying to run the auth or nfs examples. Both are rejecting similarly:

```
Trying to open request no 801035401 as safe-auth:AAAAAC--1IkAAAAAAAAAAAAAACJuZXQubWFpZHNhZmUuZXhhbXBsZXMubmZzUmVhZFdyaXRlAAAAAAAAAAAjTm9kZUpTIGV4YW1wbGUgQXBwIC0gTkZTIHJlYWQvd3JpdGUAAAAAAAAACE1haWRTYWZlAAAAAAAAAAACAAAAAAAAAAdfcHVibGljAAAAAAAAAAUAAAAAAAAAAQAAAAIAAAADAAAABAAAAAAAAAAMX3B1YmxpY05hbWVzAAAAAAAAAAUAAAAAAAAAAQAAAAIAAAADAAAABA==
Error ::  Error: Error occured opening safe-auth:AAAAAC--1IkAAAAAAAAAAAAAACJuZXQubWFpZHNhZmUuZXhhbXBsZXMubmZzUmVhZFdyaXRlAAAAAAAAAAAjTm9kZUpTIGV4YW1wbGUgQXBwIC0gTkZTIHJlYWQvd3JpdGUAAAAAAAAACE1haWRTYWZlAAAAAAAAAAACAAAAAAAAAAdfcHVibGljAAAAAAAAAAUAAAAAAAAAAQAAAAIAAAADAAAABAAAAAAAAAAMX3B1YmxpY05hbWVzAAAAAAAAAAUAAAAAAAAAAQAAAAIAAAADAAAABA== : -1
    at Object.openUri (/Volumes/Data/Projects/safe-dev/forks/safe_app_nodejs/src/native/_system_uri.js:24:11)
    at safeApp.initializeApp.then.then.res (/Volumes/Data/Projects/safe-dev/forks/safe_app_nodejs/examples/nfs_file.js:54:18)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by gnunicorn** [comment] 2017-02-13 12:44
@joshuef Unfortunately MacOS only allows you to register the URL if you have it specified in plist-file inside a bundle. While we are doing development, the beaker browser doesn't have that feature yet..

**Comment by joshuef** [comment] 2017-02-13 13:33
@gnunicorn aha. Okay fair enough! Any chance of a link to a repo that show's what you mean. I'd happily implement it locally to continue exploring the new APIs

**Comment by ethanpailes** [comment] 2017-02-21 17:58
What is the expected behavior here. Is the openUrl call supposed to pop the beaker browser open with this url? When I copy paste an auth url into the safe browser (after installing the safe authenticator plugin), it just says that the URL is malformed (which makes sense because I don't think it is standards compliant).

**Comment by bochaco** [comment] 2017-12-18 18:06
@ethanpailes , probably too late, but yes, the `openUri` function should open the browser and trigger the authenticator's popup. This is assuming you previously registered the authenticator's URI by launching the browser at least once beforehand.

I'm closing this as it's not an issue anymore, we've fixed our example electron apps and browser electron app to correctly register the URI on OS X platform.

**Closed by bochaco** 2017-12-18 18:06 UTC
