### ISSUE TITLE
Entries.forEach returns object value for entry

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_app_nodejs#190] opened 2017-12-09 17:00 UTC
I have the following snippet that yields unexpected behaviour (in the browser). The `forEach` method calls the callback with an entry that doesn't seem to be a buffer:

```
(async () => {
    const info        = { id: '1', name: '2', vendor: '3' };
    const permissions = {  };
    const options     = { own_container: true };

    const appHandle = await window.safeApp.initialise(info);
    const uri       = await window.safeApp.authorise(appHandle, permissions, options);
    await window.safeApp.connectAuthorised(appHandle, uri);

    const mdHandle = await window.safeApp.getOwnContainer(appHandle)
    const entriesHandle = await window.safeMutableData.getEntries(mdHandle)
    await window.safeMutableDataEntries.insert(entriesHandle, 'test-key', 'test-value')

    await window.safeMutableDataEntries.forEach(entriesHandle, (buffer, valueVersion) => {
      console.dir(buffer) // Outputs weird object instead of Buffer. <<-------------------
    })
    
    await window.safeMutableDataEntries.free(entriesHandle)
    await window.safeApp.free(appHandle)
})()
```

Can anyone verify this in either the browser or with NodeJS?

**Comment by bochaco** [comment] 2017-12-11 15:03
Thanks @b-zee , I'm looking into it now.

**Comment by bochaco** [comment] 2017-12-11 15:18
I'm closing this as this is a duplicate of issue [#114](https://github.com/maidsafe/beaker-plugin-safe-app/issues/114) in the beaker-plugin-safe-app and the issue is actually in the beaker plugin.

**Closed by bochaco** 2017-12-11 15:18 UTC
